
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='munievents',
    version='0.1.0',
    python_requires='==3.*,>=3.8.0',
    author='Magdalena Surowka',
    author_email='magdalena@surowka.ch',
    entry_points={"console_scripts": ["munievents = munievents.main:app.run_server"]},
    packages=['munievents'],
    package_dir={"": "."},
    package_data={},
    install_requires=['dash==1.*,>=1.18.1', 'dash-cytoscape==0.*,>=0.2.0', 'dash-html-components==1.*,>=1.1.1', 'networkx==2.*,>=2.5.0', 'pandas==1.*,>=1.2.0', 'requests==2.*,>=2.25.1'],
    extras_require={"dev": ["black==20.*,>=20.8.0.b1", "dephell==0.*,>=0.8.3"]},
)
